

INSERT INTO `provinces` (`matp`, `name`, `created_at`, `updated_at`) VALUES
('1', 'Hà Nội', NULL, NULL),
('10', 'Lào Cai', NULL, NULL),
('11', 'Điện Biên', NULL, NULL),
('12', 'Lai Châu', NULL, NULL),
('14', 'Sơn La', NULL, NULL),
('15', 'Yên Bái', NULL, NULL),
('17', 'Hoà Bình', NULL, NULL),
('19', 'Thái Nguyên', NULL, NULL),
('2', 'Hà Giang', NULL, NULL),
('20', 'Lạng Sơn', NULL, NULL),
('22', 'Quảng Ninh', NULL, NULL),
('24', 'Bắc Giang', NULL, NULL),
('25', 'Phú Thọ', NULL, NULL),
('26', 'Vĩnh Phúc', NULL, NULL),
('27', 'Bắc Ninh', NULL, NULL),
('30', 'Hải Dương', NULL, NULL),
('31', 'Thành phố Hải Phòng', NULL, NULL),
('33', 'Hưng Yên', NULL, NULL),
('34', 'Thái Bình', NULL, NULL),
('35', 'Hà Nam', NULL, NULL),
('36', 'Nam Định', NULL, NULL),
('37', 'Ninh Bình', NULL, NULL),
('38', 'Thanh Hóa', NULL, NULL),
('4', 'Cao Bằng', NULL, NULL),
('40', 'Nghệ An', NULL, NULL),
('42', 'Hà Tĩnh', NULL, NULL),
('44', 'Quảng Bình', NULL, NULL),
('45', 'Quảng Trị', NULL, NULL),
('46', 'Thừa Thiên Huế', NULL, NULL),
('48', 'Thành phố Đà Nẵng', NULL, NULL),
('49', 'Quảng Nam', NULL, NULL),
('51', 'Quảng Ngãi', NULL, NULL),
('52', 'Bình Định', NULL, NULL),
('54', 'Phú Yên', NULL, NULL),
('56', 'Khánh Hòa', NULL, NULL),
('58', 'Ninh Thuận', NULL, NULL),
('6', 'Bắc Kạn', NULL, NULL),
('60', 'Bình Thuận', NULL, NULL),
('62', 'Kon Tum', NULL, NULL),
('64', 'Gia Lai', NULL, NULL),
('66', 'Đắk Lắk', NULL, NULL),
('67', 'Đắk Nông', NULL, NULL),
('68', 'Lâm Đồng', NULL, NULL),
('70', 'Bình Phước', NULL, NULL),
('72', 'Tây Ninh', NULL, NULL),
('74', 'Bình Dương', NULL, NULL),
('75', 'Đồng Nai', NULL, NULL),
('77', 'Bà Rịa - Vũng Tàu', NULL, NULL),
('79', 'Thành phố Hồ Chí Minh', NULL, NULL),
('8', 'Tuyên Quang', NULL, NULL),
('80', 'Long An', NULL, NULL),
('82', 'Tiền Giang', NULL, NULL),
('83', 'Bến Tre', NULL, NULL),
('84', 'Trà Vinh', NULL, NULL),
('86', 'Vĩnh Long', NULL, NULL),
('87', 'Đồng Tháp', NULL, NULL),
('89', 'An Giang', NULL, NULL),
('91', 'Kiên Giang', NULL, NULL),
('92', 'Thành phố Cần Thơ', NULL, NULL),
('93', 'Hậu Giang', NULL, NULL),
('94', 'Sóc Trăng', NULL, NULL),
('95', 'Bạc Liêu', NULL, NULL),
('96', 'Cà Mau', NULL, NULL);
